# This is a Dropwizard-based Microservice
# See https://dropwizard.github.io/dropwizard/manual/configuration.html

# Group Id to publish artifacts to
groupId: com.adobe

# Artifact Id to publish AEM binaries
aemDispatcherArtifactId: dispatcher

# Root URL to download AEM binaries from
aemBinariesRootUrl: "https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher.html"

# Url parts to download the artifacts
aemBinariesUrlParts: "/${version}/dispatcher-${version}-${classifier}.${type}"

# HTTP Client settings
httpClient:
  connectionTimeout: 2s
  timeout: 5s
  timeToLive: 1h
  cookiesEnabled: false
  retries: 2
  userAgent: Maven AemBinaries Proxy

# Jetty configuration
server:
  # Disable gzip compression to avoid corruption of tar.gz files
  gzip:
    enabled: false

# Logging configuration
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: target/logs/maven-aembinaries-proxy.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: target/logs/maven-aembinaries-proxy-%d.log
      archivedFileCount: 5
